name: HikariSync-Core
version: '1.0.0'
main: me.eventually.hikarisync.core.HikariSyncCore
api-version: '1.20'
load: STARTUP
authors: [ Eventually ]
description: HikariSync Plugin core, need addons to provide features.
